# Generated by Django 5.0.4 on 2024-05-13 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'покупатель',
                'verbose_name_plural': 'покупатели',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='RealEstateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'тип недвижимостей',
                'verbose_name_plural': 'типы недвижимостей',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('house_number', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('building_number', models.IntegerField(blank=True, null=True, verbose_name='Номер корпуса')),
                ('apartment_number', models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена недвижимости')),
                ('currency', models.CharField(choices=[('USD', 'Доллар США'), ('TMT', 'Туркменский манат')], default='USD', max_length=3, verbose_name='Валюта')),
                ('total_area', models.FloatField(verbose_name='Общая площадь m²')),
                ('rooms_count', models.IntegerField(verbose_name='Количество комнат')),
                ('floors_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество этажей')),
                ('floor', models.IntegerField(blank=True, default=0, null=True, verbose_name='Этаж')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('year_built', models.IntegerField(default=2024, verbose_name='Год постройки')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_estate.city', verbose_name='Город')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_updater', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_estate.realestatetype', verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'недвижимость',
                'verbose_name_plural': 'недвижимости',
            },
        ),
        migrations.CreateModel(
            name='RealEstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='real_estate_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.realestate', verbose_name='Недвижимость')),
            ],
            options={
                'verbose_name': 'изображение недвижимости',
                'verbose_name_plural': 'изображения недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_completed', models.BooleanField(default=False, verbose_name='Сделка завершена')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='real_estate.buyer')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='real_estate.realestate')),
            ],
            options={
                'verbose_name': 'сделка',
                'verbose_name_plural': 'сделки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер квитанции')),
                ('payment_type', models.CharField(choices=[('T', 'Перечисление'), ('C', 'Наличная оплата')], default='C', max_length=1, verbose_name='Форма оплаты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='real_estate.transaction', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплаты',
            },
        ),
    ]
