# Generated by Django 5.0.4 on 2024-05-02 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('apartment', 'Квартира'), ('cottage', 'Коттедж'), ('house', 'Дом')], default='apartment', max_length=20, verbose_name='Тип недвижимости')),
                ('price', models.IntegerField()),
                ('total_area', models.FloatField()),
                ('living_area', models.FloatField(blank=True, null=True)),
                ('kitchen_area', models.FloatField(blank=True, null=True)),
                ('rooms', models.IntegerField()),
                ('balconies', models.IntegerField(default=0)),
                ('number_of_floors', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField()),
                ('description', models.TextField()),
                ('year_built', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_estate.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='real_estate_images/%Y/%m/%d/')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.realestate')),
            ],
        ),
    ]
