# Generated by Django 5.0.4 on 2024-05-13 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='building_number',
        ),
        migrations.AddField(
            model_name='realestate',
            name='building',
            field=models.IntegerField(blank=True, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма сделки'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='real_estate.buyer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сделки'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='real_estate.realestate', verbose_name='Недвижимость'),
        ),
    ]
