# Generated by Django 5.0.4 on 2024-05-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
