# Generated by Django 5.0.4 on 2024-05-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_remove_realestate_building_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='floors_count',
        ),
        migrations.AddField(
            model_name='realestate',
            name='cost_per_sqm',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Фактическая стоимость за квадратный метр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='entrance_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер подъезда'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фактическая стоимость недвижимости'),
        ),
    ]
