# Generated by Django 5.0.4 on 2024-05-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_alter_realestate_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('TMT', 'Turkmenistan Manat')], default='USD', max_length=3),
        ),
    ]
