# Generated by Django 5.0.4 on 2024-05-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_remove_realestate_floors_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='real_estate.transaction', verbose_name='Сделка'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='building',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер дома'),
        ),
    ]
