# Generated by Django 5.0.4 on 2024-05-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_alter_city_options_alter_realestate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='price',
        ),
        migrations.AddField(
            model_name='realestate',
            name='total_cost',
            field=models.IntegerField(default=0, verbose_name='Цена недвижимости'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='floor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='kitchen_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь кухни m²'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='living_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Жилая площадь m²'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='number_of_floors',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='total_area',
            field=models.FloatField(verbose_name='Общая площадь m²'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='year_built',
            field=models.IntegerField(default=2024, verbose_name='Год постройки'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='real_estate.client')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='real_estate.realestate')),
            ],
        ),
    ]
