# Generated by Django 5.0.4 on 2024-05-16 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_alter_payment_transaction_alter_realestate_building_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
            },
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='title',
        ),
        migrations.AddField(
            model_name='realestate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estates', to='real_estate.project', verbose_name='Объект'),
        ),
    ]
