# Generated by Django 5.0.4 on 2024-05-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_project_remove_realestate_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='floors_count',
            field=models.IntegerField(default=0, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('T', 'Перечисление'), ('C', 'Наличная оплата'), ('M', 'Взаиморассчет')], default='C', max_length=1, verbose_name='Форма оплаты'),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тип недвижимости'),
        ),
    ]
