# Generated by Django 5.0.4 on 2024-06-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_realestate_floors_count_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='apartment_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры (офиса, магазина)'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='cost_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактическая стоимость за квадратный метр'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Фактическая стоимость недвижимости'),
        ),
    ]
