# Generated by Django 5.0.4 on 2024-05-10 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_alter_payment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'покупатель', 'verbose_name_plural': 'покупатели'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'оплата', 'verbose_name_plural': 'оплаты'},
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='number_of_floors',
            new_name='floors_count',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='rooms',
            new_name='rooms_count',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='balconies',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='kitchen_area',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='living_area',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('T', 'Перечисление'), ('C', 'Наличная оплата')], default='C', max_length=1, verbose_name='Форма оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер квитанции'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='apartment_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='building_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер корпуса'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='house_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='real_estate.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
