# Generated by Django 5.0.4 on 2024-06-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'локация',
                'verbose_name_plural': 'локации',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Гос. номер')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('brand', models.CharField(max_length=255, verbose_name='Марка')),
                ('imei', models.CharField(max_length=20, verbose_name='IMEI')),
                ('number_sim', models.CharField(max_length=20, verbose_name='Номер SIM')),
                ('gps_model', models.CharField(max_length=50, verbose_name='Модель GPS трекера')),
                ('installation_date', models.DateField(verbose_name='Дата установки')),
                ('holder', models.CharField(max_length=100, verbose_name='Предохранитель держатель')),
                ('fuse_5a', models.CharField(max_length=50, verbose_name='Предохранитель 5A')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('executor', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
    ]
