# Generated by Django 5.0.4 on 2024-06-25 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSTrackerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель GPS трекера')),
            ],
            options={
                'verbose_name': 'Модель GPS трекера',
                'verbose_name_plural': 'Модели GPS трекеров',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('work_order_number', models.CharField(max_length=100, verbose_name='Номер заказа на работу')),
                ('mechanic', models.CharField(max_length=100, verbose_name='Механик')),
            ],
            options={
                'verbose_name': 'Запись о техническом обслуживании',
                'verbose_name_plural': 'Записи о техническом обслуживании',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название запчасти')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
        migrations.CreateModel(
            name='SparePartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер заказа')),
                ('date', models.DateField(verbose_name='Дата')),
                ('warehouse', models.CharField(max_length=100, verbose_name='Склад')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
            ],
            options={
                'verbose_name': 'Заказ запчастей',
                'verbose_name_plural': 'Заказы запчастей',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бренда')),
            ],
            options={
                'verbose_name': 'Бренд транспортного средства',
                'verbose_name_plural': 'Бренды транспортных средств',
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория транспортного средства')),
            ],
            options={
                'verbose_name': 'Категория транспортного средства',
                'verbose_name_plural': 'Категории транспортных средств',
            },
        ),
        migrations.CreateModel(
            name='VehicleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название транспортного средства')),
            ],
            options={
                'verbose_name': 'Название транспортного средства',
                'verbose_name_plural': 'Названия транспортных средств',
            },
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='vehicle.maintenancerecord', verbose_name='Запись о техническом обслуживании')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.sparepart', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Запчасть для техобслуживания',
                'verbose_name_plural': 'Запчасти для техобслуживания',
            },
        ),
        migrations.CreateModel(
            name='SparePartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vehicle.sparepartorder', verbose_name='Заказ')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.sparepart', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Элемент заказа запчастей',
                'verbose_name_plural': 'Элементы заказов запчастей',
            },
        ),
        migrations.AddField(
            model_name='sparepartorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.supplier', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регистрационный номер')),
                ('vin', models.CharField(blank=True, max_length=100, null=True, verbose_name='VIN')),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер двигателя')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Дата установки')),
                ('gps_tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.gpstrackermodel', verbose_name='GPS трекер')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.location', verbose_name='Локация')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclebrand', verbose_name='Бренд')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehiclecategory', verbose_name='Категория')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclename', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicle.vehicle', verbose_name='Транспортное средство'),
        ),
    ]
