# Generated by Django 5.0.4 on 2024-07-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Тип топлива',
                'verbose_name_plural': 'Типы топлива',
            },
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество топлива')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='vehicle.vehicle', verbose_name='Транспорт')),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.fueltype', verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Запись заправки топлива',
                'verbose_name_plural': 'Записи заправки топлива',
            },
        ),
        migrations.CreateModel(
            name='OilChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата замены масла')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег на момент замены масла')),
                ('next_oil_change_date', models.DateField(blank=True, null=True, verbose_name='Дата следующей замены масла')),
                ('next_oil_change_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег для следующей замены масла')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_change_records', to='vehicle.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Запись замены масла',
                'verbose_name_plural': 'Записи замены масла',
            },
        ),
        migrations.CreateModel(
            name='VehicleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('condition', models.CharField(choices=[('working', 'Работает'), ('not_working', 'Не работает')], max_length=20, verbose_name='Состояние')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='vehicle.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Состояние транспортного средства',
                'verbose_name_plural': 'Состояния транспортных средств',
            },
        ),
    ]
