# Generated by Django 5.0.4 on 2024-07-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_fueltype_fuelrecord_oilchangerecord_vehiclecondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='total_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общий пробег'),
        ),
    ]
