# Generated by Django 5.0.4 on 2024-06-12 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_brand_alter_vehicle_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Модель GPS трекера')),
            ],
            options={
                'verbose_name': 'модель GPS трекера',
                'verbose_name_plural': 'модели GPS трекеров',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'наименование',
                'verbose_name_plural': 'наименования',
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gps_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.gpsmodel', verbose_name='Модель GPS трекера'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.name', verbose_name='Наименование'),
        ),
    ]
