# Generated by Django 5.0.4 on 2024-08-29 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_dailyreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'verbose_name': 'Ежедневный отчет', 'verbose_name_plural': 'Ежедневные отчеты'},
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата отчета'),
        ),
    ]
