# Generated by Django 5.0.4 on 2024-09-01 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_dailyreport_options_alter_dailyreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Когда отчет отправлен'),
            preserve_default=False,
        ),
    ]
